name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: huggingface/hub-sync@v0.1.0
        with:
          github_repo_id: ${{ github.repository }}
          huggingface_repo_id: Arrsssa/2555038-2026.09.07
          hf_token: ${{ secrets.HF_TOKEN }}
